# Generated by Django 4.1.4 on 2023-01-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='myblog.tag'),
        ),
    ]
