# Generated by Django 4.1.4 on 2023-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quote',
        ),
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
